# write-dashboard-status.ps1 - emit YaE's own status JSON for the dashboard.
#
# Every project repo feeds status/data/<id>.json on release; YaE itself was
# the one project without a writer, so the Everything card had no status
# data. This runs inside YaE's release BEFORE push-to-github, so the JSON
# rides the same commit - no self-commit, no self-push.
#
# Read-modify-write: the audit + barRaise blocks are owned by the review
# skills and are preserved verbatim; this script only refreshes the
# release-owned fields.

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
# Canonical-first since 2026-08-19: status data is written to the private
# PortfolioOps repo, and the public copy under status\data here is GENERATED by
# the projector. Writers never touch the public file directly.
$DataDir = "X:\PortfolioOps\status\data"
if (-not (Test-Path $DataDir)) { New-Item -ItemType Directory -Path $DataDir -Force | Out-Null }
$JsonPath = Join-Path $DataDir "Everything.json"

$ctx = $null
try { $ctx = Get-Content -Raw -Encoding utf8 (Join-Path $RepoRoot ".project-context.json") | ConvertFrom-Json } catch { $ctx = $null }

$headRaw = (& git -C $RepoRoot log -1 --pretty="%h|%cI|%s" 2>$null)
$head = @("", "", "")
if ($headRaw) { $head = $headRaw -split "\|", 3 }

$existing = $null
if (Test-Path $JsonPath) {
  try { $existing = Get-Content -Raw -Encoding utf8 $JsonPath | ConvertFrom-Json } catch { $existing = $null }
}

$msg = $head[2]
if ($msg -and $msg.Length -gt 160) { $msg = $msg.Substring(0, 157) + "..." }

# observability-05 (2026-09-23): stale used to be a literal false, so the
# dashboard's freshness badge and its stale-project counter could never fire
# for this project. It is computed from the real age of the newest signal:
# the last commit (this site has no releases apart from commits), the last
# review report, or the last audit. Fourteen days with none of the three is
# stale, and the reason names the ages so the card can say why.
$staleFlag = $false
$staleReason = $null
try {
  $signals = @()
  if ($head[1]) { $signals += @{ name = "last commit"; at = [DateTimeOffset]::Parse($head[1]) } }
  if ($existing -and $existing.barRaise -and $existing.barRaise.latestReportAt) {
    $signals += @{ name = "last review"; at = [DateTimeOffset]::Parse($existing.barRaise.latestReportAt) }
  }
  if ($existing -and $existing.audit -and $existing.audit.lastRunAt) {
    $signals += @{ name = "last audit"; at = [DateTimeOffset]::Parse($existing.audit.lastRunAt) }
  }
  if ($signals.Count -gt 0) {
    $newest = $signals | Sort-Object { $_.at } -Descending | Select-Object -First 1
    $ageDays = [math]::Floor(([DateTimeOffset]::Now - $newest.at).TotalDays)
    if ($ageDays -ge 14) {
      $staleFlag = $true
      $staleReason = "nothing published for $ageDays days; the newest signal is the $($newest.name) at $($newest.at.ToString('yyyy-MM-dd'))"
    }
  }
} catch {
  # An unparseable timestamp is not staleness; the write goes on with the flag down.
}

$payload = [ordered]@{
  project = "Everything"
  displayName = $(if ($ctx -and $ctx.display_name) { $ctx.display_name } else { "Yes& Everything" })
  version = $head[0]   # no semver on the umbrella site; HEAD short sha stands in
  lastReleaseAt = $head[1]
  lastReleaseMessage = $msg
  milestone = $(if ($ctx -and $ctx.milestone) { $ctx.milestone } else { $null })
  completion = $(if ($ctx -and $ctx.completion) { [ordered]@{ pct = $ctx.completion.pct; anchored = $ctx.completion.anchored } } else { $null })
  itemsLeft = $(if ($ctx -and $ctx.completion -and $ctx.completion.remaining) { [ordered]@{ gates = @($ctx.completion.remaining).Count } } else { $null })
  repoUrl = "https://github.com/TheProphetKane/yesandeverything"
  workTreeClean = $true   # the release commits everything, this file included
  audit = $(if ($existing -and $existing.audit) { $existing.audit } else { $null })
  barRaise = $(if ($existing -and $existing.barRaise) { $existing.barRaise } else { $null })
  stale = $staleFlag
  # Cleared on every successful write, so a reason from a previous failure
  # cannot outlive the failure it described (data-integrity-03). Set here only
  # when the age rule above fired.
  staleReason = $staleReason
  tags = $(if ($ctx -and $ctx.tags) { $ctx.tags } else { @("static-site", "orchestration", "release-pipeline", "public-voice") })
}

# paused / retired: a project Kane has paused (D81, 2026-09-22) or retired carries the block
# in this same file, written by the portfolio session that applied the ruling. This writer
# rebuilds the payload from the context and the repo, so without this the next status write
# erased the block (Agents lost its paused block at 20:09 on 2026-09-22, minutes after it was
# written). Preserved verbatim like audit and barRaise; absent keys stay absent.
if ($existing -and $existing.paused) { $payload.paused = $existing.paused }
if ($existing -and $existing.retired) { $payload.retired = $existing.retired }

$json = ($payload | ConvertTo-Json -Depth 6) -replace "`r`n", "`n"
if (-not $json.EndsWith("`n")) { $json += "`n" }
$tmp = "$JsonPath.tmp"
[System.IO.File]::WriteAllText($tmp, $json, [System.Text.UTF8Encoding]::new($false))
$null = (Get-Content -Raw -Encoding utf8 $tmp | ConvertFrom-Json)   # parse before replacing the live file
Move-Item -Force $tmp $JsonPath
$back = [System.IO.File]::ReadAllText($JsonPath)
if ($back.Contains([char]0)) { throw "NUL bytes in $JsonPath after write" }
$null = ($back | ConvertFrom-Json)                   # fresh-read re-parse (FUSE guard)

# Project the public copy into status\data here; it rides the release commit.
python "X:\PortfolioOps\scripts\project-status.py" Everything
if ($LASTEXITCODE -ne 0) { throw "status projection failed for Everything; public copy not refreshed" }
Write-Host "Wrote canonical Everything.json and projected the public copy (HEAD $($head[0]))." -ForegroundColor Green
